spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha # 按字母顺序排序接口
  api-docs:
    path: /v3/api-docs      # OpenAPI 文档的 JSON 路径
  default-produces-media-type: application/json # 默认响应类型
  default-consumes-media-type: application/json # 默认请求类型

# DeepSeek 配置（OpenAI 兼容接口）
deepseek:
  base-url: "https://api.deepseek.com/v1/chat/completions"
  api-key: "${DEEPSEEK_API_KEY:sk-64ba3bd1e1b04331a066c331f6c6aab6}"
  model: "deepseek-chat"
